### ISSUE TITLE
Getting a weird segfault with addOrUpdatePage

### ISSUE THREAD

**Issue by starstuffharvestingstarlight** [philproctor/confluence-cli#5]
Hi all, I'm using this tool to write a decently sized post, it's causing a segfault. I'm not sure exactly what might be going on. Is there a timeout setting or something like that?

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6665ff]

goroutine 1 [running]:
github.com/proctorlabs/confluence-cli/client.(*ConfluenceClient).AddPage(0xc0000b6680, 0x7ffdf93372b7, 0xe, 0x7ffdf93372a2, 0x4, 0xc00010c000, 0x16cb, 0x2f268045)
	/home/hc/go/src/github.com/proctorlabs/confluence-cli/client/pages.go:19 +0x20f
github.com/proctorlabs/confluence-cli/command.addOrUpdatePage()
	/home/hc/go/src/github.com/proctorlabs/confluence-cli/command/add-page.go:36 +0x2a5
github.com/proctorlabs/confluence-cli/command.Run(0x7ffdf93372d3, 0x12, 0xc0000b62c0, 0xc000102000)
	/home/hc/go/src/github.com/proctorlabs/confluence-cli/command/run.go:23 +0x2b3
main.main()
	/home/hc/go/src/github.com/proctorlabs/confluence-cli/main.go:30 +0x67b
) = ?
+++ exited with 2 +++
```

I ran `strace` on this and saw a few of these:

```
futex(0x98c960, FUTEX_WAIT_PRIVATE, 0, {tv_sec=0, tv_nsec=1263485}) = -1 ETIMEDOUT (Connection timed out)
```
I have no connection issues at all on any other tool, and can edit confluence directly.

**Comment by starstuffharvestingstarlight** [comment]
Could this be related to a URL that has been changed ? The wiki I'm testing at was renamed recently, and some tasks had the old URL.
